# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.rbruce.DataDemo.DataDemo
name: ${project.name}
version: ${project.version}
author: Charlie Burris, Dr. Rebecca Bruce
description: ${project.description}
commands:
  message:
    description: set the greeting message
    usage: /<command> greeting message
    permission: DataDemo.message
  god:
    description: gives the lighting bolt power
    usage: /<command> 
    permission: DataDemo.god
  human:
    description: removes the lighting bolt power
    usage: /<command> 
    permission: DataDemo.human  
  sword:
    description: gives player a sword
    usage: /<command> 
    permission: DataDemo.sword
  armor:
    description: gives player a set of armor
    usage: /<command> 
    permission: DataDemo.armor    
permissions:
  DataDemo.*:
    description: gives all permissions of the plugin commands
    default: true
    children:
      DataDemo.message:
        default: op 
      DataDemo.god:
        default: true
      DataDemo.human:
        default: true
      DataDemo.spider:
        default: true
      DataDemo.bed:
        default: op
      DataDemo.xp:
        default: true
      DataDemo.sword:
        default: true
      DataDemo.armor:
        default: true
